### ISSUE TITLE
Build fails for browserify versions newer than 4.x

### ISSUE THREAD

**Issue by scharf** [openannotation/annotator#459]
When I run `make` or `tools/build annotator ` the build fails: 
```
$ tools/build  annotator

/Users/scharf/git/openannotation/annotator/node_modules/browserify/index.js:664
        throw new Error(
              ^
Error: bundle() no longer accepts option arguments.
Move all option arguments to the browserify() constructor.
    at Browserify.bundle (/Users/scharf/git/openannotation/annotator/node_modules/browserify/index.js:664:15)
    at pack (/Users/scharf/git/openannotation/annotator/tools/build:259:9)
    at core (/Users/scharf/git/openannotation/annotator/tools/build:165:5)
    at node.toStringWithSourceMap.file (/Users/scharf/git/openannotation/annotator/tools/build:92:9)
    at ChildProcess.exithandler (child_process.js:646:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
```

If I install browserify 4.2.3 (the last version in the 4.x stream) the build succeeds.

`npm install .`  has installed browserify version 6.3.2

**Comment by tilgovi** [comment]
This is no longer the case, I think. The master branch currently is using `^8.1.0` as the version string for browserify.
